### ISSUE TITLE
Enable custom kmer size

### ISSUE THREAD

**Issue by SorenKarst** [rrwick/Filtlong#13]
Hi Ryan,

Thanks for a great tool.

Would it be possible to enable use of different kmer sizes for --trim --split?

regards
Søren

**Comment by rrwick** [comment]
I'm afraid that no it couldn't, at least not without a lot of re-engineering. I use 16-mers because I can fit them neatly into 32-bit integers - a fact I exploit to make Filtlong relatively fast. More flexible k-mer sizes would necessitate more general (and probably slower) ways of tracking k-mers.

Also, I'm not sure if other k-mer sizes would do much better. 16-mers seem to work pretty well for matching Nanopore reads to an accurate reference (like an Illumina read/assembly). A typical Nanopore read has about 90% identity, so longer k-mers could become difficult to match (e.g. exact match 30-mers would be rare in a Nanopore read). And shorter k-mers become less useful (e.g. a 9-mer would often find a match by random chance).

I'm going to close this issue because I doubt I'll ever implement flexible k-mer sizes, but I am curious if you have other thoughts on the matter. Thanks!

Ryan

**Comment by SorenKarst** [comment]
Thanks for taking the time to consider my proposal.

I agree that large kmers and nanopore data doesn't make a lot of sense right now. I am doing some experimental work, where it makes sense to screen the smaller kmers to look for "signal" (11 to 16), but I completely understand that this is outside the scope of your intention for the filtlong tool.

For now I have a hacky implementation of jellyfish and awk, that performs similarly to your filtlong --trim --split with smaller kmers. If the proof of concept looks convincing, I might try to change your mind ;)
