### ISSUE TITLE
How apply min_mean_q

### ISSUE THREAD

**Issue by Pstege** [rrwick/Filtlong#40]
Hello,

I try to use the option --window_q_weight to trim read-ends using Filtlong v0.2.1.
I, however, cannot get it to work. I therefore first tried to use the more simple --min_mean_q setting and this also does not work.
I ran this ridiculous example, which should result in zero reads: 
_filtlong --min_length 200 --mean_q_weight 10 --min_mean_q 50 reads.fastq | gzip > reads_q50.fq.gz_

I also tried this with phred of 12 and without the --mean_q_weight argument, but the result is always that all reads are reported in the output.
Verbose output does not show phred scores but something else : 
_9bd..number; length = 2492; mean quality = 98.72; window quality = 98.72_

The reads are not the problem, since this does work and results in the expected 0 reads:
_chopper -q 50 -l 200 -i reads.fastq > reads_q50.fq.gz_

Am I doing something wrong? 
Thank you in advance for your time!

Cheers,
Paul

**Comment by Pstege** [comment]
Ah I only now see this post:
https://github.com/rrwick/Filtlong/issues/18#issuecomment-526209403

Is this advice still the best option?

**Comment by rrwick** [comment]
Hi Paul,

I somewhat regret this decision in hindsight, but the `--min_mean_q` and `--min_window_q` options aren't based on a [qscore](https://en.wikipedia.org/wiki/Phred_quality_score) but rather on an estimate of read identity. They really should have used `_id` instead of `_q` for clarity.

So your filter value of `--min_mean_q 50` says to exclude reads with <50% identity. That's an incredibly low threshold, so all (or nearly all) of the reads will pass. If you mean Q50, then you should use `--min_mean_q 99.999`, which will probably exclude all reads.

Ryan
