### ISSUE TITLE
--min_length and --keep_percent parameters?

### ISSUE THREAD

**Issue by jaimiewest** [rrwick/Filtlong#41]
I am curious how you arrive at decisions regarding optimal --min_length and --keep_percent. In your 'perfect bacterial genome' tutorial, you use 6000 and 90%, which works well, but I am wondering if this is worth playing around with. Here in the filtlong documentation you use min_length of 1000, and that is what I have coming off the GridION.
I am getting not ideal assemblies and wondering how much I can do in silica before troubleshooting in the lab.

Thanks.

**Comment by rrwick** [comment]
What would be 'best' for these thresholds will depend on your read set, genome and downstream analysis, and it's often just a best guess! But here are some general principles:
* The deeper your read set is, the more aggressive you can be with the thresholds (higher `--min_length` and lower `--keep_percent`), because if you have a lot of reads, you can afford to lose more of them.
* If your ONT reads have already been QCed by MinKNOW (i.e. you're only using 'pass' reads), then you can be more relaxed (higher `--keep_percent`).
* If your genome has small plasmids, you need to be be careful with Filtlong or else you might lose the small plasmids in your reads.

For example, when I've had a very deep read set where I know there are no small plasmids, I'll be aggressive and use `--min_length 10000`. This results in very clean assemblies, assuming you still have enough reads. But if I know (or suspect) there are small plasmids, I might use `--min_length 1000` instead.

Good luck with your in silico troubleshooting, but in my experience if a read set isn't assembling well, then troubleshooting in the lab is needed.

Ryan
